### PR TITLE
Add Bibliothèque et Archives nationales du Québec entry.

### PR DESCRIPTION
**Pull request by eric-gagnon**
Thanks for Openseadragon, it's been a production for a while, just realized that we could add our entry while visiting the site. We use it with Cantaloupe image server, also an amazing software.

### CODE REVIEW

**Comment by iangilman** [comment]
Wonderful! Looks good. Unfortunately, however, this repository is just for the built version of the site. To change the actual source code for the site, please make a new pull request off of this file in the site-build repository:

https://github.com/openseadragon/site-build/blob/master/www/in-the-wild.html

Sorry for the confusing setup!

Also, we're trying to keep the list alphabetized, so please add your entry below "Arkyves". I see we've let "Biblissima portal" and "Beni Hassan" go in out of order; feel free to swap them while you're in there!

Thank you for doing this!

**Comment by eric-gagnon** [comment]
Ah, ok I'll redo the pull request.
I did notice the alphabetical order and was not sure what to do about it, I'll fix it too.
Thanks!

**Comment by iangilman** [comment]
Great, thank you! :)

**Comment by iangilman** [comment]
@eric-gagnon Looks like you haven't made the new pull request in the other project yet?

**Comment by eric-gagnon** [comment]
@iangilman Yes sorry for that, I will follow-up and complete it.

**Comment by iangilman** [comment]
@eric-gagnon It doesn't look like you made a new PR for this over in the `site-build` repository... Is that the case? Would you still be up for doing so?

**Pull request closed without merging**
